# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
    name: azure-agent
    steps:
    - script: echo "AKS"
      displayName: "Run aone line script"

    - task: DownloadSecureFile@1
      name: devops.secureFilepath
      inputs:
        secureFile: 'devops.pub'

    - task: TerraformCLI@2
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)https://github.com/Devops-Engineer-24/azure-devops-kubernetes-terraform-pipeline/tree/main/configuration/iaac/azure/kubernetes'
        commandOptions: '-var client_id =$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(devops.secureFilePath)'
        backendType: 'azurerm'
        backendServiceArm: 'aks-connection'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmResourceGroupLocation: 'eastasia'
        backendAzureRmStorageAccountName: 'terraform-rg-aks-backend-sa'
        backendAzureRmContainerName: 'terraform-rg-aks-backend'
        backendAzureRmKey: 'Kubernetes-dev-state'
        allowTelemetryCollection: true