trigger:
- main

pool:
  name: azure-agent

steps:
- script: echo "AKS"
  displayName: "Run a one-line script"

# Download secure file
- task: DownloadSecureFile@1
  name: DownloadSSHKey
  inputs:
    secureFile: 'devops.pub'

# Install Terraform
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Initialize Terraform
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="ssh_public_key=$(DownloadSSHKey.secureFilePath)"'
    backendType: 'azurerm'
    backendServiceArm: 'aks-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-rg'
    backendAzureRmResourceGroupLocation: 'eastasia'
    backendAzureRmStorageAccountName: 'tfaksbackendsa'
    backendAzureRmContainerName: 'terraform-rg-aks-backend'
    backendAzureRmKey: 'Kubernetes-dev-state'
    allowTelemetryCollection: true


- task: TerraformCLI@2
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'aks-connection'
    commandOptions: '-var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="ssh_public_key=$(DownloadSSHKey.secureFilePath)'
    allowTelemetryCollection: false

