
trigger:
- main

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
     - bash: echo Build FirstJob
  - job: SecondJob
    steps:
       - bash: echo Build SecondJobs
- stage: DevDeploy
  jobs:
    - job: Deploy
      steps:
       - bash: echo Dev Deploy
- stage: QaDeploy
  jobs:
    - job: QaDeploy
      steps:
       - bash: echo Qa Deploy
- stage: ProdDeploy
  jobs:
    - job: PROD
      steps:
        - bash: echo Prod Deploy  



