
trigger:
- main

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
     - script: echo Build FirstJob
     - script: echo $(Build.BuildNumber)
     - script: echo $(Build.BuildID)
     - script: echo $(Build.SourceBranchName)
     - script: echo $(Build.SourcesDirectory)
     - script: echo $(System.DefaultWorkingDirectory)
     - script: echo $(Build.ArtifactStagingDirectory)
     - script: echo $(projectName)
     - script: java -version
     - script: python --version
    # - script: mvn -version
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: |
           **/*.yaml
           **/*.tf
         TargetFolder: 'echo $(Build.ArtifactStagingDirectory)'

  - job: SecondJob
    steps:
       - script: echo Build SecondJobs
- stage: DevDeploy
  variables:
    enviromnet: Dev
  dependsOn: Build
  jobs:
    - job: Deploy
      steps:
       - script: echo Dev Deploy
       - script: echo echo $(PIPELINELEVALVARIABLE)Dev
- stage: QaDeploy
  dependsOn: Build
  jobs:
    - job: QaDeploy
      steps:
       - script: echo Qa Deploy
- stage: ProdDeploy
  dependsOn: 
  - QaDeploy
  - DevDeploy
  jobs:
    - job: ProdDeploy
      steps:
        - script: echo Prod Deploy  





