# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildID)'

stages:
- stage: Build
  displayName: Build image
  pool:
      name: docker-agent
  jobs:
  - job: Build
    displayName: Build
    steps:
      
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'Azure-Pipe;ine'
        repository: 'mayur24/azure-pipeline'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: CopyFiles@2
      inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.yaml'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: docker-agent
    steps:
  
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactDirectory)'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'EKS-Cluster-Connection'
        namespace: 'default'
        manifests: '$(System.ArtifactDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'mayur24/azure-pipeline:$(tag)'
