# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 97

stages:
- stage: Build
  displayName: Build image
  pool:
      name: docker-agent
  jobs:
  - job: Build
    displayName: Build
    steps:
 #   - task: Docker@2
  #    displayName: Build an image
  #    inputs:
  #      command: build
   #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
   #     tags: |
    #      $(tag)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Systeam.DefaultWorkingDirctory)'
        Contents: '**'
        TargetFolder: '$(Systeam.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: docker-agent
    steps:
  
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(Systeam.ArtifactDirectory)'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'EKS-Cluster-Connection'
        namespace: 'default'
        manifests: '$(Systeam.ArtifactDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'in28min/currency-exchange-devops:$(tag)'
