trigger:
  branches:
    include:
      - main

jobs:
- job: SelfHostedPoolJob
  displayName: Run job on Default Agent Pool
  pool:
    name: docker-agent
  steps:
    - script: echo "This job is running on the Dcoker Agent Pool."
      displayName: 'Show Pool Information'

    - script: |
        echo Performing tasks on the dcoker agent...
        - script: mvn -version
        - bash: ls -lhrt
        echo Add your commands here!
      displayName: 'Run Tasks'
