trigger:
  branches:
    include:
      - main

jobs:
- job: DefaultPoolJob
  displayName: Run job on Default Agent Pool
  pool:
    name: Default
  steps:
    - script: echo "This job is running on the Default Agent Pool."
      displayName: 'Show Pool Information'

    - script: |
        echo Performing tasks on the default agent...
        echo Add your commands here!
      displayName: 'Run Tasks'
